version: '3.8'

services:
  youtube-kids:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: youtube-kids-app
    ports:
      - "8341:3000"
    volumes:
      # Mount thư mục chứa video trên Host vào trong Container
      - ./public/videos:/app/public/videos
      # Mount thư mục Database SQLite để hỗ trợ ghi file temp (-wal, -shm) tránh lỗi readonly
      - ./prisma:/app/prisma
    restart: always
